

services:
  # --- 1. Сервис Базы данных (MySQL) ---
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: joilloij
      MYSQL_DATABASE: sexshopwarehouse_db
    ports:
      # для доступа с хоста (например, через MySQL Workbench)
      - "3307:3306"
    volumes:
      # Для сохранения данных между перезапусками
      - mysql_data:/var/lib/mysql

  # --- 2. Сервис Бэкенда (ASP.NET) ---
  backend:
    build:
      context: ./SexShopWarehouseAPI
      dockerfile: Dockerfile
    container_name: aspnet-backend
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=localhost;Database=sexshopwarehouse_db;User=root;Password=joilloij;"
    depends_on:
      - db
    restart: on-failure

  # --- 3. Сервис Фронтенда (React + Nginx) ---
  frontend:
    build:
      context: SexShopWarehouseApp
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend 
    

# --- 4. Volumes ---
volumes:
  mysql_data: # Именованный том для сохранения данных MySQL